=== ananmika/synergy-objective-xml/Mkrtich.Adamyan/XSD/Resources/Validators/Recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<xs:complexType name="steps">
  <xs:sequence>
    <xs:element name="step" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="ingredients">
  <xs:sequence>
    <xs:element name="ingredient" type="ingredient" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="ingredient">
  <xs:sequence>
    <xs:element name="quantity" type="xs:decimal" minOccurs="0"/>
    <xs:element name="measurementUnit" type="xs:string" minOccurs="0"/>
    <xs:element name="name" type="xs:string"/>
  </xs:sequence>
	<xs:attribute name="state" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="cook">
  <xs:sequence>
    <xs:element name="duration" type="xs:duration"/>
    <xs:element name="steps" type="steps"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="attrString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="imgSource" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="recipe">
	<xs:sequence>
		<xs:element name="name" type="attrString"/>
		<xs:element name="countryOfOrigin" type="xs:string"/>
		<xs:element name="ingredients" type="ingredients"/>
		<xs:element name="cooking" type="cook"/>
	</xs:sequence>
	<xs:attribute name="category" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="recipes">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="recipe" type="recipe" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== ananmika/synergy-objective-xml/Mkrtich.Adamyan/XSD/Recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Resources\RecipesStyleSheet.xsl"?>

<recipes 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="Resources\Validators\Recipes.xsd">
	<recipe category="dessert">
		<name imgSource="Resources\Images\lemon_cupcakes.jpg">Lemon Cupcakes</name>
		<countryOfOrigin>Great Britain</countryOfOrigin>
		<ingredients>
			<ingredient>
				<quantity>3</quantity>
				<measurementUnit> cups</measurementUnit>
				<name>self-rising flour</name>
			</ingredient>
			<ingredient>
				<quantity>1.5</quantity>
				<measurementUnit> teaspoon</measurementUnit>
				<name>salt</name>
			</ingredient>
			<ingredient state="divided">
				<quantity>1</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>whole milk</name>
			</ingredient>
			<ingredient state="divided">
				<quantity>2.5</quantity>
				<measurementUnit> tablespoons</measurementUnit>
				<name>fresh lemon juice</name>
			</ingredient>
			<ingredient state="at room temperature">
				<quantity>1</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>unsalted butter</name>
			</ingredient>
			<ingredient>
				<quantity>2</quantity>
				<measurementUnit> cups</measurementUnit>
				<name>white sugar</name>
			</ingredient>
			<ingredient>
				<quantity>1</quantity>
				<measurementUnit> teaspoon</measurementUnit>
				<name>vanilla extract</name>
			</ingredient>
			<ingredient>
				<quantity>1.5</quantity>
				<measurementUnit> teaspoon</measurementUnit>
				<name>salt</name>
			</ingredient>
			<ingredient>
				<quantity>2</quantity>
				<measurementUnit> tablespoons</measurementUnit>
				<name>lemon zest</name>
			</ingredient>
			<ingredient state="at room temperature">
				<quantity>4</quantity>
				<name>eggs</name>
			</ingredient>
			<ingredient>
				<quantity>2</quantity>
				<measurementUnit> cups</measurementUnit>
				<name>chilled heavy cream</name>
			</ingredient>
			<ingredient>
				<quantity>0.75</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>confectioners' sugar</name>
			</ingredient>
			<ingredient>
				<quantity>1.5</quantity>
				<measurementUnit> tablespoons</measurementUnit>
				<name>fresh lemon juice</name>
			</ingredient>
		</ingredients>
		<cooking>
			<duration>PT1H25M</duration>
			<steps>
				<step>
					Preheat oven to 375 degrees F (190 degrees C). Line 30 cupcake pan cups with paper liners.
				</step>
				<step>
					Sift the self-rising flour and salt together in a bowl. In another bowl, beat the unsalted butter and sugar with an electric mixer until light and fluffy. Beat in the eggs one at a time, beating each egg until incorporated before adding the next. Mix in the vanilla extract and lemon zest.
				</step>
				<step>
					Gently beat the flour mixture into the butter mixture, one third at a time, alternating with half the milk and half the lemon juice after each of the first 2 additions of flour. Beat until just combined; do not over mix.
				</step>
				<step>
					Fill the prepared cupcake liners with batter 3/4 full, and bake in the preheated oven until a toothpick inserted in the center comes out clean, about 17 minutes. Let the cupcakes cool in the pans for about 10 minutes before removing them to finish cooling on a rack.
				</step>
				<step>
					To make the icing, beat the cream in a chilled bowl with an electric mixer set on Low until the cream begins to thicken. Add the confectioners' sugar and lemon juice, a little at a time, beating after each addition, until fully incorporated. Increase the mixer speed to High, and beat until the icing forms soft peaks, about 5 minutes. Spread on the cooled cupcakes. Refrigerate leftovers.
				</step>
			</steps>
		</cooking>
	</recipe>	
	<recipe category="main dish">
		<name imgSource="Resources\Images\slow_cooker_pulled_pork.jpg">Slow Cooker Pulled Pork</name>
		<countryOfOrigin>Austria</countryOfOrigin>
		<ingredients>
			<ingredient>
				<quantity>2</quantity>
				<measurementUnit> pound</measurementUnit>
				<name>pork tenderloin</name>
			</ingredient>
			<ingredient>
				<quantity>12</quantity>
				<measurementUnit> fluid ounce</measurementUnit>
				<name>root beer</name>
			</ingredient>
			<ingredient>
				<quantity>18</quantity>
				<measurementUnit> ounce</measurementUnit>
				<name>barbeque sauce</name>
			</ingredient>
			<ingredient state="split and lightly toasted">
				<quantity>8</quantity>
				<name>hamburger buns</name>
			</ingredient>
		</ingredients>
		<cooking>
			<duration>PT7H10M</duration>
			<steps>
				<step>
					Place the pork tenderloin in a slow cooker; pour the root beer over the meat. Cover and cook on low until well cooked and the pork shreds easily, 6 to 7 hours. Note: the actual length of time may vary according to individual slow cooker. Drain well. Stir in barbecue sauce. Serve over hamburger buns.
				</step>
			</steps>
		</cooking>
	</recipe>	
	<recipe category="main dish">
		<name imgSource="Resources\Images\cola_onion_pork_chops.jpg">Cola Onion Pork Chops</name>
		<countryOfOrigin>Austria</countryOfOrigin>
		<ingredients>
			<ingredient>
				<quantity>3</quantity>
				<name>3 thick cut boneless pork chops</name>
			</ingredient>
			<ingredient>
				<quantity>12</quantity>
				<measurementUnit> fluid ounce</measurementUnit>
				<name>cola-flavored carbonated beverage</name>
			</ingredient>
			<ingredient>
				<quantity>1</quantity>
				<measurementUnit> ounce</measurementUnit>
				<name>dry onion soup mix</name>
			</ingredient>
		</ingredients>
		<cooking>
			<duration>PT1H5M</duration>
			<steps>
				<step>
					Preheat the oven to 350 degrees F (175 degrees C).	
				</step>
				<step>
					Place the pork chops in a shallow glass baking dish. Pour the cola over them, and sprinkle with onion soup mix.
				</step>
				<step>
					Bake uncovered for 30 minutes in the preheated oven. Turn over, and continue baking for another 30 minutes, until sauce is thickened and chops are fork tender.	
				</step>
			</steps>
		</cooking>
	</recipe>
	<recipe category="main dish">
		<name imgSource="Resources\Images\shrimp_lemon_pepper_linguini.jpg">Shrimp Lemon Pepper Linguini</name>
		<countryOfOrigin>Great Britain</countryOfOrigin>
		<ingredients>
			<ingredient>
				<quantity>8</quantity>
				<measurementUnit> ounce</measurementUnit>
				<name>linguine pasta</name>
			</ingredient>
			<ingredient>
				<quantity>1</quantity>
				<measurementUnit> teaspoon</measurementUnit>
				<name>olive oil</name>
			</ingredient>
			<ingredient state="minced">
				<quantity>6</quantity>
				<measurementUnit> cloves</measurementUnit>
				<name>garlic</name>
			</ingredient>
			<ingredient>
				<quantity>0.5</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>chicken broth</name>
			</ingredient>
			<ingredient>
				<quantity>0.25</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>whie wine</name>
			</ingredient>
			<ingredient state="juiced">
				<quantity>1</quantity>
				<name>lemon</name>
			</ingredient>
			<ingredient>
				<quantity>0.5</quantity>
				<measurementUnit> teaspoon</measurementUnit>
				<name>lemon zest</name>
			</ingredient>
			<ingredient>
				<name>salt</name>
			</ingredient>
			<ingredient>
				<quantity>2</quantity>
				<measurementUnit> tablespoons</measurementUnit>
				<name>freshly ground black pepper</name>
			</ingredient>
			<ingredient state="peeled and deveined">
				<quantity>1</quantity>
				<measurementUnit> pound</measurementUnit>
				<name>fresh shrimp</name>
			</ingredient>
			<ingredient>
				<quantity>0.25</quantity>
				<measurementUnit> cup</measurementUnit>
				<name>butter</name>
			</ingredient>
			<ingredient>
				<quantity>3</quantity>
				<measurementUnit> tablespoons</measurementUnit>
				<name>chopped fresh parsley</name>
			</ingredient>
			<ingredient>
				<quantity>1</quantity>
				<measurementUnit> tablespoon</measurementUnit>
				<name>chopped fresh basil</name>
			</ingredient>
		</ingredients>
		<cooking>
			<duration>PT40M</duration>
			<steps>
				<step>
					Bring a large pot of lightly salted water to a boil. Add linguine, and cook for 9 to 13 minutes or until al dente; drain.	
				</step>
				<step>
					Heat oil in a large saucepan over medium heat, and saute garlic about 1 minute. Mix in chicken broth, wine, lemon juice, lemon zest, salt, and pepper. Reduce heat, and simmer until liquid is reduced by about 1/2.
				</step>
				<step>
					Mix shrimp, butter, parsley, and basil into the saucepan. Cook 2 to 3 minutes, until shrimp is opaque. Stir in the cooked linguine, and continue cooking 2 minutes, until well coated.
				</step>
			</steps>
		</cooking>
	</recipe>	
</recipes>
